### ISSUE TITLE
Add a header with a h1 to index.html ...

### ISSUE THREAD

**Issue by lihatu** [ellienndea/fcc-berlin-fun#2]
Add a header including a \<h1> to index.html saying "freeCodeCamp Berlin Fun GitHub Project".  The style should be black and white with 'courier new, monospace font family' to keep it neutral.

**Comment by NaincyKumariKnoldus** [comment]
Hey ! I have raised a PR for this. Please review my PR.
Thanks!

**Comment by ghost** [comment]
Ok, I will take care of this :)
(I'm Holger)
