### ISSUE TITLE
Style the menu in index.html

### ISSUE THREAD

**Issue by lihatu** [ellienndea/fcc-berlin-fun#3]
Style the menu in index.html. It should be black and white with 'new courier, monospace' font family to keep it neutral. Should be big enough to read on different screen sizes and have hover style, focus style, active style and visited.

**Comment by G3n1tiv** [comment]
Hi, please assign me to this.

**Comment by SammyShehter** [comment]
[X](https://github.com/ellienndea/fcc-berlin-fun/pull/7)
